// This file is automatically generated. Do not modify it manually.
// You can publish a new version of this file by running `npx firebase-frameworks-tools client:web --config=.firebase/hosting.json --out src/firebase/config.ts`

export const firebaseConfig = {
  "apiKey": "mock-api-key",
  "authDomain": "studio-7771091082-4e1c2.firebaseapp.com",
  "projectId": "studio-7771091082-4e1c2",
  "storageBucket": "studio-7771091082-4e1c2.appspot.com",
  "messagingSenderId": "7771091082",
  "appId": "1:7771091082:web:65e8a514d3393910c51d6c",
  "measurementId": "G-MOCK12345"
};
